// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArW1KMQ0HG3I_HZE61ZOOzvzSr5JACrYM',
    appId: '1:1016600015524:web:bd184e1d3d243531d8ac31',
    messagingSenderId: '1016600015524',
    projectId: 'cloudbelly-5b13e',
    authDomain: 'cloudbelly-5b13e.firebaseapp.com',
    storageBucket: 'cloudbelly-5b13e.appspot.com',
    measurementId: 'G-QSD15Q66PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAecKQQqWGcOraG87msjUHrBl8kG72toIY',
    appId: '1:1016600015524:android:c2b9e662f80fc3a8d8ac31',
    messagingSenderId: '1016600015524',
    projectId: 'cloudbelly-5b13e',
    storageBucket: 'cloudbelly-5b13e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA58nxI-QVN6ru7nqp7nj0tFyhdquxi4xU',
    appId: '1:1016600015524:ios:05a19bd4c080bd65d8ac31',
    messagingSenderId: '1016600015524',
    projectId: 'cloudbelly-5b13e',
    storageBucket: 'cloudbelly-5b13e.appspot.com',
    androidClientId: '1016600015524-k69t8jsvmiunopfs1cp5lp0ieqdd77r4.apps.googleusercontent.com',
    iosClientId: '1016600015524-1u0hou3m1b5dnv624i7ailkuef2d8psq.apps.googleusercontent.com',
    iosBundleId: 'com.example.codebellyApp',
  );
}
